// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsfrkycayhymzmqamnsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzZnJreWNheWh5bXptcWFtbnN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3Nzc0OTYsImV4cCI6MjA3MzM1MzQ5Nn0.O9RmZiilRAJqvJC1Hl6Bb2UMpWWsIAbqQ60Qr1u-L0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});